* Classic ASP
  by [[Lang]]. <2009-07-17 Fri>

  I'm currently working in classic ASP, which supports javascript as
  server-side language. I'd like to get John Resig's [[http://ejohn.org/blog/bringing-the-browser-to-the-server/][env.js]] working
  in ASP if we continue to use this platform.

** Order of script evaluation
   Classic ASP supports a few different language platforms, although
   it seems rare to see anything other than VBScript and JScript. The
   order of evaluation is:

   0. The language tag.
   1. =<script>= tags in the non-default language.
   2. =<script>= tags in the default language.
   3. Static HTML and =<% %>= blocks in order.

   There are some restrictions on the type of data that can be passed
   between languages, but functions appear to be fair game. I've had
   success programming in JScript by leaving the default language
   alone and preparing thunks that produce output. I can call those
   thunks in the page as =<% foo_thunk %>=.

   I've had even better success dumping JSON to the client and keeping
   the HTML on the client side.
