#+TITLE: Orangesoda Index

[[file:sitemap.org][Sitemap]] and [[file:license.org][License]]. Everything on this site falls under the license
unless otherwise noted.

* Recent Changes
  - [[./windows.org][Windows Cheat Sheet]] also moved to it's own file, [2010-03-31 Wed].
  - [[./emacs.org][Emacs]] moved to it's own file, [2010-03-31 Wed].
  - [[file:squash/index.org][Squash]] by [[file:lang.org][Lang]], [2010-03-11 Thu]. A new version, r2.

* Javascript
** Fluid Bindings (aka Dynamic Scoping, aka Parameters)
   <<fluid.js>> by [[file:lang.org][Lang]]. [2009-07-17 Fri]

   Fluid bindings follow the flow of control rather than the lexical
   order of a program. See wikipedia on [[http://en.wikipedia.org/wiki/Scope_%28programming%29#Dynamic_scoping][Dynamic Scoping]].

   The code: [[./javascript/fluid.js][fluid.js]].

** jquery.dataset: HTML5 Dataset jQuery Plugin
   Posted by [[Ben]] on [2009-09-08 Tue].

   The HTML5 specification allows [[http://dev.w3.org/html5/spec/Overview.html#attr-data][custom data attributes]] to be added
   to any DOM element.  This jQuery plugin provides methods to
   retrieve and manipulate custom attributes.

   Read More: [[./jquery.dataset.org][The jquery.dataset Plugin]]

   Download: [[./javascript/jquery.dataset.js][jquery.dataset.js]]

** Squash: SQL Manipulation with Native Expressions
   <<squash>> by [[file:lang.org][Lang]]. [2009-12-07 Mon]

   This is an incomplete implementation of SQL in JavaScript objects.
   It's in the spirit of LINQ, but adds an additional layer of
   abstraction; clauses are interpreted with late-binding. It's
   possible to use the same set of where clauses in multiple contexts.

   [[file:squash][Squash]].

* Scheme
** A =REQUIRE= special form for Gambit-C
Posted by [[Ben]] on [2009-07-22 Wed].

The =REQUIRE= special form includes libraries only once.  It is
implemented using [[http://www.iro.umontreal.ca/~gambit/][Gambit-C]]'s =INCLUDE= and =LOAD= forms with
=COND-EXPAND= to prevent a library from being loaded again (which is
an error) or re-evaluated.

=REQUIRE= accepts a sequence of requirement specifications that
identify libraries.  The specifications are mapped onto the filesystem
to find the corresponding source files or compiled modules.  For
example:

#+BEGIN_SRC scheme
(require (srfi 1)
         (lib util))

;; Library code here...
#+END_SRC

See [[http://github.com/weaver/gambit-prelude/blob/master/require%23.scm][require#.scm]] for additional documentation.  An easy way to
integrate =REQUIRE= into a project is to include [[http://github.com/weaver/gambit-prelude/blob/master/require%23.scm][require#.scm]] from
`.gambcini' or `~/.gambcini'.  For more details, see [[http://www.iro.umontreal.ca/~gambit/doc/gambit-c.html#Customization-1][Customization]] in
the Gambit-C documentation.

Source: [[http://github.com/weaver/gambit-prelude/blob/master/require%23.scm][require#.scm]] [[http://github.com/weaver/gambit-prelude/blob/master/_require.scm][_require.scm]]

* Contributers
** <<Ben>> Weaver
   [[http://benweaver.com/][Ben]] lives in Chattanooga TN and works at [[http://thisismedium.com/][Medium]].  You can follow
   him on [[http://twitter.com/bwvr][Twitter]], see code on [[http://github.com/weaver][github]], or send an email to
   [his-first-name] at orangesoda.net.

** <<Lang>> Martin
   [[file:lang.org][Lang]] is also in Chattanooga. I don't really do social networking; I
   do have an account at [[http://github.com/langmartin][github]]. You can email lang.martin at Gmail.

* Wibler.com
  Wibler email & apps are hosted by Google:
  - [[http://mail.google.com/a/wibler.com/][email]]
  - [[http://www.google.com/calendar/a/wibler.com/][calendar]]


