#+TITLE: Lang Martin
[[./index.org][Home]]

Email lang.martin at Gmail.

I use Github to store repositories of most of my projects. My account
there is http://github.com/langmartin.

* Project Index
  - [[file:emacs.org][Emacs]] :: Code and notes.
  - [[file:windows.org][Windows Cheat Sheet]] :: I'm using Windows (XP) for the first time
       in years, I'm collecting notes as I go.
  - [[file:squash/index.org][Squash]] :: a JavaScript library for manipulating SQL queries.
  - [[file:jsmacs/index.org][JSMacs]] :: an early-stage, slow-moving attempt to get emacs lisp
              and emacs running in the browser.
  - [[http://github.com/weaver/sic][SIC]] :: Scheme Incremental Compiler.

* Ideas
** Chrome plugin: tab key focuses form elements
   http://github.com/decklin/yakshave/ is a comprehensive keyboard
   capture plugin; I'd like to make the tab key focus only form
   elements until you start searching for links.

** Emacs interface to Chrome Dev Tools
   [[http://code.google.com/p/chromedevtools/wiki/ChromeDevToolsProtocol][ChromeDevToolsProtocol]].

** Emacs interface to Google contacts
   I'd like to use the BBDB keys from Gnus against my Google contacts.
