#+TITLE: Windows Cheat Sheet
[[./index.org][Home]] [[./lang.org][Up]]

* Autohotkey
  by [[./lang.org][Lang]], [2010-03-31 Wed]

  [[http://www.autohotkey.com/][Autohotkey]] is a scripting language for manipulation windows inputs.
  It works well for mapping Caps Lock to Control. My [[./windows/remap.ahk][remapping script]].
  The top few lines do basic rebinding, the rest of the file maps
  Shift + Scroll Wheel to Horizontal Scroll Wheel in Firefox. That's
  the default behavior on OS X, and I got used to it.

* Classic ASP Order of Evaluation
  by [[file:lang.org][Lang]]. [2009-07-17 Fri]

  Classic ASP supports a few different language platforms, although
  it seems rare to see anything other than VBScript and JScript. The
  order of evaluation is:

  0. The language tag.
  1. =<script>= tags in the non-default language.
  2. =<script>= tags in the default language.
  3. Static HTML and =<% %>= blocks in order.

  There are some restrictions on the type of data that can be passed
  between languages, but functions appear to be fair game. I've had
  success programming in JScript by leaving the default language
  alone and preparing thunks that produce output. I can call those
  thunks in the page as =<% foo_thunk %>=.

  I've had even better success dumping JSON to the client and keeping
  the HTML on the client side.

* Disable Console Beep
  The CMD window on XP uses the internal PC speaker beep. Stop it, and
  set it to not start on boot:

  : net stop beep
  : sc config beep start= disabled

  The CMD window will manage ok over ssh with =TERM=xterm=.

* Firefox
  by [[./lang.org][Lang]], [2010-03-31 Wed]

  These notes aren't really windows specific.

  - =browser.tabs.closeButtons= :: 2 will hide the close buttons.
       More tab text real estate.
  - =browser.tabs.tabMinWidth= :: reduce from 100 to allow more tabs
       without the drop down.
  - =browser.sessionstore.interval= :: increase to fix choppy video
       (maybe not necessary > 3.5).
  - =extensions.checkCompatibility.3.6= :: create boolean false to
       enable extensions that aren't marked ready for the new
       version.
  - =mousewheel.withshiftkey.action= :: 0 to make it scroll
       horizontally.
  - =network.cookie.lifetime.days= :: expire all cookies in...
  - =network.cookie.lifetimePolicy= :: 3 to honor lifetime.days.

* Fonts
  - [[http://www.microsoft.com/downloads/details.aspx?familyid=22e69ae4-7e40-4807-8a86-b3d36fab68d3&displaylang=en][Consolas]] :: Nice monospace font if ClearType is on.
  - [[http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=DoulosSILfont][DoulosSIL]] :: missing unicode glyphs.

* IE Debugging
  =HKEY_CURRENT_USER\Software\Microsoft\Internet Explorer\Main=,
  =Disable Script Debugger= and =DisableScriptDebuggerIE=.
  =Friendly http errors=.

* Keyboard Shortcuts
  1. Paste without Formatting :: In MS Office, you can "Paste Special"
     to remove formatting with =C-A-v=. You can also paste with =C-v=
     and then re-highlight the pasted text and hit =C-<space>= to
     clear the formatting after the fact.

* Installation Notes
** Emacs
   Unzip emacs, install the GnuWin32 image libraries. Add the
   libraries to the PATH for the system or user. In =emacs/bin=, run
   =addpm.exe=.

** GPG
   Change the home directory of GnuPG by setting the environment
   variable =GNUPGHOME=.

** Chrome
   Download specific versions of chrome: [[http://dl.google.com/chrome/install/472.59/chrome_installer.exe][Chrome 6.0.472.59]]. This is
   really only useful with Chrome Portable; for portable you need to
   unpack the installer with 7-zip rather than running it. The
   Chrome-bin directory just goes in the portable app.

   As of [2010-10-20 Wed], via [[http://googlechromereleases.blogspot.com/][the Chrome release blog]]:

   | Stable | [[http://dl.google.com/chrome/install/517.41/chrome_installer.exe][Chrome 7.0.517.41]] |
   | Beta   | [[http://dl.google.com/chrome/install/517.41/chrome_installer.exe][Chrome 7.0.517.41]] |
   | Dev    | [[http://dl.google.com/chrome/install/552.5/chrome_installer.exe][Chrome 8.0.552.5]]  |
